# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: '>=15.10.0'

      - name: Gather stats
        run: |
          export SECRET_GITHUB_PERSONAL_ACCESS_TOKEN=${{ github.token }}
          export NO_TTY=TRUE
          npm install
          node gather_stats.js

      - name: Push data back to GitHub
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "run gather_stats.js"
          git push origin gh-pages
